import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import { updateGuideMarkdown, writeGuideVersions, checkGuideVersions, staleGuideVersions } from './guide-versions.mjs';

test('updates the actual shadcn install command and CDN pins without changing definition versions', () => {
  const source = 'OODS Foundry 0.6.0. This describes 0.6.0.\n```bash\nnpm install @oods/foundry@0.6.0\n```\n[guide](https://cdn.jsdelivr.net/npm/@oods/foundry@0.6.0/COMPONENTS.md)\n```yaml\nversion: 0.6.0\n```\nStage1 v0.3.0 and `other-package` 0.2.0.\n';
  const actual = updateGuideMarkdown(source, '0.6.1');
  assert(actual.includes('npm install @oods/foundry@0.6.1'));
  assert(actual.includes('@oods/foundry@0.6.1/COMPONENTS.md'));
  assert(actual.includes('This describes 0.6.1.'));
  assert(actual.includes('version: 0.6.0'));
  assert(actual.includes('Stage1 v0.3.0 and `other-package` 0.2.0.'));
  assert.deepEqual(staleGuideVersions('This describes 0.6.0. `census-0.5.0.json`', '0.6.1'), ['0.6.0']);
});

test('authored guide updates leave generated README and release history to their owners', () => {
  const parent = path.resolve('.tmp'); fs.mkdirSync(parent, { recursive: true });
  const folder = fs.mkdtempSync(path.join(parent, 's231-guide-versions-'));
  try {
    fs.writeFileSync(path.join(folder, 'package.json'), JSON.stringify({ version: '0.6.1' }));
    const readme = '<!-- Generated by scripts/runtime/client-configs.mjs -->\nOODS Foundry 0.6.0\n';
    fs.writeFileSync(path.join(folder, 'README.md'), readme);
    fs.writeFileSync(path.join(folder, 'COMPONENTS.md'), 'npm install @oods/foundry@0.6.0\n');
    fs.writeFileSync(path.join(folder, 'CHANGELOG.md'), 'OODS Foundry 0.6.0\n');
    assert.deepEqual(writeGuideVersions(folder), ['COMPONENTS.md']);
    assert.equal(fs.readFileSync(path.join(folder, 'README.md'), 'utf8'), readme);
    assert.equal(fs.readFileSync(path.join(folder, 'CHANGELOG.md'), 'utf8'), 'OODS Foundry 0.6.0\n');
    assert.deepEqual(checkGuideVersions(folder).map(row => row.file), ['README.md']);
  } finally { fs.rmSync(folder, { recursive: true, force: true }); }
});
