import { defineComponent, h, ref, useId, watch, type PropType } from 'vue';
import { DEFAULT_COLOR_STATES, formatReadOnlyValue, geoFieldMapping, recipeItemLabels, traitEventRows, type GeoFieldMappingValue, type TraitEventKind } from '@oods/component-contracts';
import { Checkbox, Input, Select } from './fields.js';
import { ColorSwatch } from './breadth.js';

const array = Array as PropType<readonly unknown[]>;
function eventRecipe(id: string, kind: TraitEventKind, title: string) {
  return defineComponent({ name: id, props: { id: String, title: { type: String, default: title }, archivedAt: String as PropType<string | null>, restoredAt: String as PropType<string | null>, archivedBy: String as PropType<string | null>, reason: String as PropType<string | null>, timestamp: String as PropType<string | null>, code: String as PropType<string | null>, history: array, status: String as PropType<string | null>, showActor: { type: Boolean, default: true }, showReason: { type: Boolean, default: true } }, setup: props => () => {
    const rows = traitEventRows(kind, props);
    // s223-m01 (#2527 ruling 7): a card with no events renders nothing, as in React and HTML.
    if (!rows.length) return null;
    return h('article', { id: props.id, class: 'oods-trait-recipe', 'data-oods-component': id, 'aria-label': props.title }, [h('h2', props.title), h('ol', rows.map((row, index) => h('li', { key: index }, [h('strong', row.title), h('p', row.at ? h('time', { datetime: row.at }, row.time) : row.time), row.actor && h('p', `Actor: ${row.actor}`), row.reason && h('p', `Reason: ${row.reason}`), row.code && h('p', `Code: ${row.code}`)])))]);
  } });
}
export const ArchiveEvent = eventRecipe('ArchiveEvent', 'archive', 'Archive events');
export const CancellationEvent = eventRecipe('CancellationEvent', 'cancellation', 'Cancellation event');
export const StateTransitionEvent = eventRecipe('StateTransitionEvent', 'transition', 'State transitions');
export const CommunicationDetailPanel = defineComponent({ name: 'CommunicationDetailPanel', props: { id: String, title: { type: String, default: 'Communication' }, channels: array, templates: array, policies: array, conversations: array }, setup: props => () => h('section', { id: props.id, class: 'oods-trait-recipe', 'data-oods-component': 'CommunicationDetailPanel', 'aria-label': props.title }, [h('h2', props.title), h('div', { role: 'status', 'aria-live': 'polite' }, `${props.conversations?.length ?? 0} conversations`), h('dl', ([['Channels', props.channels], ['Templates', props.templates], ['Delivery policies', props.policies], ['Conversations', props.conversations]] as const).map(([label, rows]) => h('div', { key: label }, [h('dt', label), h('dd', rows?.length ? h('ul', recipeItemLabels(rows).map((text, index) => h('li', { key: index }, text))) : 'None recorded')])))] ) });

export const ColorStatePicker = defineComponent({ name: 'ColorStatePicker', props: { id: String, title: { type: String, default: 'Color state' }, colorStates: { type: Array as PropType<readonly string[]>, default: () => [...DEFAULT_COLOR_STATES] }, value: String, disabled: Boolean }, emits: { change: (value: string) => typeof value === 'string' }, setup(props, { emit }) {
  const generatedId = useId(); const selected = ref(props.value ?? props.colorStates[0] ?? '');
  watch(() => [props.value, props.colorStates], () => { selected.value = props.value ?? props.colorStates[0] ?? ''; });
  return () => h('fieldset', { id: props.id, class: 'oods-trait-recipe', 'data-oods-component': 'ColorStatePicker' }, [h('legend', props.title), h(Select, { id: `${props.id ?? generatedId}-state`, label: 'Color state', name: 'color_state', modelValue: selected.value, disabled: props.disabled, options: [...(!props.colorStates.includes(selected.value) ? [{ value: selected.value, label: selected.value || 'Choose state', disabled: true }] : []), ...props.colorStates.map(value => ({ value, label: formatReadOnlyValue(value, 'string', true) }))], 'onUpdate:modelValue': (next: string) => { selected.value = next; emit('change', next); } })]);
} });
export const StatusColorLegend = defineComponent({ name: 'StatusColorLegend', props: { id: String, title: { type: String, default: 'Status colors' }, colorStates: { type: Array as PropType<readonly string[]>, default: () => [...DEFAULT_COLOR_STATES] }, value: String, showTokenReferences: Boolean }, setup: props => () => h('section', { id: props.id, class: 'oods-trait-recipe', 'data-oods-component': 'StatusColorLegend', 'aria-label': props.title }, [h('h2', props.title), h('dl', props.colorStates.map(state => h('div', { key: state }, [h('dt', [h(ColorSwatch, { label: state, color: `var(--sys-status-${state}-surface)` }), state === props.value ? ' (current)' : '']), h('dd', props.showTokenReferences ? `--sys-status-${state}-surface` : state)])))]) });

export const GeoFieldMappingForm = defineComponent({ name: 'GeoFieldMappingForm', props: { id: String, title: { type: String, default: 'Geographic fields' }, embedded: Boolean, disabled: Boolean, latitude: String, longitude: String, identifier: String, autoDetect: { type: Boolean, default: true } }, emits: { change: (_value: GeoFieldMappingValue) => true }, setup(props, { emit }) {
  const generatedId = useId(); const value = ref(geoFieldMapping(props));
  watch(() => [props.latitude, props.longitude, props.identifier, props.autoDetect], () => { value.value = geoFieldMapping(props); });
  const update = (patch: Partial<GeoFieldMappingValue>) => { value.value = { ...value.value, ...patch }; emit('change', value.value); };
  return () => h(props.embedded ? 'fieldset' : 'form', { id: props.id, class: 'oods-trait-recipe', 'data-oods-component': 'GeoFieldMappingForm', 'aria-label': props.title, onSubmit: (event: Event) => event.preventDefault() }, [h(props.embedded ? 'legend' : 'h2', props.title), ...(['latitude', 'longitude', 'identifier'] as const).map(field => h(Input, { key: field, id: `${props.id ?? generatedId}-${field}`, name: `geo_${field}_field`, label: `${field[0].toUpperCase()}${field.slice(1)} field`, modelValue: value.value[field], disabled: props.disabled, 'onUpdate:modelValue': (next: string) => update({ [field]: next }) })), h(Checkbox, { id: `${props.id ?? generatedId}-auto`, name: 'geo_auto_detect_enabled', label: 'Auto detect fields', modelValue: value.value.autoDetect, disabled: props.disabled, 'onUpdate:modelValue': (autoDetect: boolean) => update({ autoDetect }) })]);
} });
export const GeoResolutionBadge = defineComponent({ name: 'GeoResolutionBadge', props: { id: String, resolution: String }, setup: props => () => h('span', { id: props.id, class: 'oods-geo-resolution', 'data-oods-component': 'GeoResolutionBadge' }, `Resolution: ${props.resolution || 'Not determined'}`) });
export const GeocodablePreview = defineComponent({ name: 'GeocodablePreview', props: { id: String, title: { type: String, default: 'Geographic data' }, resolution: String, requiresLookup: { type: Boolean, default: undefined }, detectedFields: array }, setup: props => () => h('section', { id: props.id, class: 'oods-trait-recipe', 'data-oods-component': 'GeocodablePreview', 'aria-label': props.title }, [h('h2', props.title), h('dl', [h('dt', 'Resolution'), h('dd', props.resolution || 'Not determined'), h('dt', 'Requires lookup'), h('dd', props.requiresLookup === undefined ? 'Not determined' : props.requiresLookup ? 'Yes' : 'No'), h('dt', 'Detected fields'), h('dd', recipeItemLabels(props.detectedFields).join(', ') || 'None detected')])]) });
