import { validateSubstitution } from '../tools/component-substitution.js';
import { sourceSpecifier, substitutionPackage, type EmittedSubstitution } from './component-substitutions.js';
import { posix } from 'node:path';
import { canonicalize, sha256 } from '@oods/artifacts';

import { localSetterSymbol, localStateSymbol } from './binding-utils.js';
import type {
  CodegenFramework,
  GeneratedArtifact,
  GeneratedArtifactAction,
  GeneratedArtifactFile,
  GeneratedDependency,
} from './types.js';

export const GENERATED_ARTIFACT_SCHEMA_VERSION = '1.0.0' as const;

type DependencyCatalogEntry = Omit<GeneratedDependency, 'name'>;

/**
 * Runtime-owned dependency versions are deliberately frozen into the wire
 * contract. Discovery-only releases preserve these published compatibility pins
 * so generated bytes remain stable; the alignment test prevents workspace ranges.
 */
export const GENERATED_DEPENDENCY_CATALOG = {
  '@oods/component-contracts': { version: '0.6.2', kind: 'dependency' },
  '@oods/component-styles': { version: '0.6.2', kind: 'dependency' },
  '@oods/components-react': { version: '0.6.2', kind: 'dependency' },
  '@oods/components-vue': { version: '0.6.2', kind: 'dependency' },
  'class-variance-authority': { version: '0.7.1', kind: 'dependency' },
  react: { version: '19.2.0', kind: 'peerDependency' },
  'react-dom': { version: '19.2.0', kind: 'peerDependency' },
  '@vue/server-renderer': { version: '3.5.42', kind: 'dependency' },
  '@vitejs/plugin-vue': { version: '5.2.4', kind: 'dependency' },
  vue: { version: '3.5.42', kind: 'peerDependency' },
} as const satisfies Record<string, DependencyCatalogEntry>;

/**
 * The Node floor a generated app declares: the published @oods packages it installs need Node 22 (s220-m02, #2463a), and
 * its build toolchain (Vite 6.4, TypeScript, vue-tsc) accepts 22.0.0. The alignment test keeps it equal to theirs.
 */
export const GENERATED_APP_NODE_FLOOR = '>=22.0.0';

const FRAMEWORK_PEERS: Record<CodegenFramework, readonly string[]> = {
  html: [],
  react: ['react', 'react-dom'],
  vue: ['vue'],
};

const FRAMEWORK_IMPORTS: Record<CodegenFramework, ReadonlySet<string>> = {
  html: new Set(),
  react: new Set([
    '@oods/component-contracts',
    '@oods/component-styles/css',
    '@oods/components-react',
    'class-variance-authority',
    'react',
    'react-dom/client',
    'react-dom/server',
  ]),
  vue: new Set([
    '@oods/component-contracts',
    '@oods/component-styles/css',
    '@oods/components-vue',
    'class-variance-authority',
    'vue',
    '@vitejs/plugin-vue',
    '@vue/server-renderer',
  ]),
};

const EMPTY_IMPORT_SET: ReadonlySet<string> = new Set();

function dependencyCatalogEntry(name: string): DependencyCatalogEntry | undefined {
  return Object.hasOwn(GENERATED_DEPENDENCY_CATALOG, name)
    ? GENERATED_DEPENDENCY_CATALOG[name as keyof typeof GENERATED_DEPENDENCY_CATALOG]
    : undefined;
}

function frameworkPeers(framework: CodegenFramework): readonly string[] {
  return Object.hasOwn(FRAMEWORK_PEERS, framework) ? FRAMEWORK_PEERS[framework] : [];
}

function frameworkImports(framework: CodegenFramework): ReadonlySet<string> {
  return Object.hasOwn(FRAMEWORK_IMPORTS, framework)
    ? FRAMEWORK_IMPORTS[framework]
    : EMPTY_IMPORT_SET;
}

const EXACT_VERSION = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
const PACKAGE_NAME = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
const CONTENT_HASH = /^sha256:[a-f0-9]{64}$/;
const JAVASCRIPT_IDENTIFIER = /^[$_\p{ID_Start}][$_\u200c\u200d\p{ID_Continue}]*$/u;

function escapePattern(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Validate the emitter's small local-state protocol, not arbitrary JavaScript.
 * Nonempty bodies alone cannot prove a binding: the input must reach its own
 * state, including Vue's intermediate setter. Dismissal is the zero-input case.
 */
function localHandlerWritesOwnState(
  framework: CodegenFramework,
  name: string,
  line: string,
  body: string,
  source: string,
): boolean {
  const parameters = line.match(new RegExp(
    `^\\s*const\\s+${escapePattern(name)}\\s*=\\s*\\(([^()]*)\\)\\s*=>`,
    'u',
  ))?.[1]?.trim();
  if (parameters === undefined) return false;
  const parameter = parameters.split(':', 1)[0]!.trim();
  if (parameter && !JAVASCRIPT_IDENTIFIER.test(parameter)) return false;
  const state = escapePattern(localStateSymbol(name));
  const setter = escapePattern(localSetterSymbol(name));
  const input = escapePattern(parameter);

  if (framework === 'react') {
    const declaration = source.match(new RegExp(
      `^\\s*const \\[${state},\\s*${setter}\\] = React\\.useState(?:<[^>\\n]+>)?\\((.*)\\);\\s*$`,
      'mu',
    ));
    if (!declaration) return false;
    if (!parameter) {
      return declaration[1] === 'true' && new RegExp(`^${setter}\\(false\\);?$`, 'u').test(body);
    }
    return new RegExp(
      `^${setter}\\(${input}(?:\\.currentTarget\\.(?:value|checked))?\\);?$`,
      'u',
    ).test(body);
  }
  if (framework !== 'vue') return false;
  const declaration = source.match(new RegExp(
    `^\\s*const ${state} = ref(?:<[^>\\n]+>)?\\((.*)\\);\\s*$`,
    'mu',
  ));
  if (!declaration) return false;
  if (!parameter) {
    return declaration[1] === 'true' && new RegExp(`^${state}\\.value = false;?$`, 'u').test(body);
  }
  if (!new RegExp(`^${setter}\\(${input}\\);?$`, 'u').test(body)) return false;
  const setterDeclaration = source.match(new RegExp(
    `^\\s*const ${setter} = \\(([^()]*)\\) => \\{\\s*(.*?)\\s*\\};\\s*$`,
    'mu',
  ));
  const setterParameter = setterDeclaration?.[1]?.split(':', 1)[0]?.trim();
  return !!setterParameter && JAVASCRIPT_IDENTIFIER.test(setterParameter)
    && new RegExp(`^${state}\\.value = ${escapePattern(setterParameter)};?$`, 'u')
      .test(setterDeclaration![2]!);
}

function compareCodePoint(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function contentHash(contents: string): string {
  return `sha256:${sha256(contents)}`;
}

function packageNameFromSpecifier(specifier: string): string | null {
  if (
    specifier.startsWith('.')
    || specifier.startsWith('/')
    || specifier.startsWith('file:')
    || specifier.startsWith('link:')
    || specifier.startsWith('workspace:')
    || specifier.startsWith('git:')
    || specifier.startsWith('http:')
    || specifier.startsWith('https:')
  ) {
    return null;
  }

  const segments = specifier.split('/');
  return specifier.startsWith('@')
    ? (segments.length >= 2 ? `${segments[0]}/${segments[1]}` : null)
    : segments[0] || null;
}

function collectBareImportSpecifiers(files: readonly GeneratedArtifactFile[]): string[] {
  const specifiers = new Set<string>();
  const importPattern = /\b(?:import|export)\s+(?:type\s+)?(?:[^'";]*?\sfrom\s*)?['"]([^'"]+)['"]/g;

  for (const file of files) {
    for (const match of file.contents.matchAll(importPattern)) {
      const specifier = match[1];
      if (!specifier) continue;
      if (packageNameFromSpecifier(specifier)) specifiers.add(specifier);
    }
  }

  return [...specifiers].sort(compareCodePoint);
}

function canonicalPayload(artifact: Omit<GeneratedArtifact, 'contentHash'>): string {
  return canonicalize(artifact);
}

function actionKey(action: GeneratedArtifactAction): string {
  return action.name;
}

function actionSourceKey(source: GeneratedArtifactAction['sources'][number]): string {
  return [source.nodeId, source.event, source.component].join('\u0000');
}

function normalizedAction(action: GeneratedArtifactAction): {
  name: string;
  parameters: GeneratedArtifactAction['parameters'];
  sources: GeneratedArtifactAction['sources'][number][];
} {
  return {
    name: action.name,
    parameters: action.parameters.map((parameter) => ({ ...parameter })),
    sources: action.sources
      .map((source) => ({ ...source }))
      .sort((left, right) => compareCodePoint(actionSourceKey(left), actionSourceKey(right))),
  };
}

/** Hash-bound source marker used to couple emitted declarations to artifact metadata. */
export function generatedActionContractDigest(action: GeneratedArtifactAction): string {
  return contentHash(canonicalize(normalizedAction(action)));
}

/** Hash-bound provenance marker for one schema declaration of a domain action. */
export function generatedActionSourceDigest(
  actionName: string,
  source: GeneratedArtifactAction['sources'][number],
): string {
  return contentHash(canonicalize({ actionName, source }));
}

export function generatedActionTypeSignature(action: GeneratedArtifactAction): string {
  const parameters = action.parameters
    .map((parameter) => `${parameter.name}: ${parameter.type}`)
    .join(', ');
  return `${action.name}: (${parameters}) => void`;
}

function artifactPath(framework: CodegenFramework, fileExtension: string): string {
  return framework === 'html' ? 'index.html' : `src/GeneratedUI${fileExtension}`;
}

function substitutionCatalog(framework: CodegenFramework, substitutions: readonly EmittedSubstitution[] = []) {
  const entries = new Map<string, DependencyCatalogEntry>();
  const imports = new Set<string>();
  const components = new Set<string>();
  const localImports = new Set<string>();
  for (const entry of substitutions) {
    if (framework === 'html') throw new Error('HTML artifacts cannot substitute framework components.');
    if (entry.source.shadcn) {
      const closure = entry.source.shadcn;
      if ((closure.framework ?? 'react') !== framework || entry.source.package || entry.source.version || !CONTENT_HASH.test(closure.closureHash) || !closure.module || closure.file.startsWith('/') || closure.file.split('/').includes('..')) throw new Error('Invalid portable shadcn substitution identity.');
      // Reuse the semantic prop checks with a harmless locator; no filesystem inspection is performed here.
      validateSubstitution({ component: entry.component, [framework]: { ...entry.source, shadcn: { project: '/project', module: closure.module } } });
      const local = (specifier: string) => specifier === closure.module || Object.keys(closure.paths).some(alias => alias.includes('*') ? specifier.startsWith(alias.slice(0, alias.indexOf('*'))) && specifier.endsWith(alias.slice(alias.indexOf('*') + 1)) : specifier === alias);
      localImports.add(closure.module); imports.add(closure.module);
      for (const specifier of closure.imports) { imports.add(specifier); if (local(specifier)) localImports.add(specifier); }
      for (const integration of ['@tailwindcss/vite', '@tailwindcss/postcss']) if (closure.dependencies[integration]) imports.add(integration);
      for (const [name, version] of Object.entries(closure.dependencies)) {
        if (dependencyCatalogEntry(name) && !['react', 'react-dom', 'vue', '@vue/server-renderer'].includes(name)) continue;
        if (!PACKAGE_NAME.test(name) || !EXACT_VERSION.test(version)) throw new Error(`Invalid shadcn dependency ${name}@${version}.`);
        if (entries.has(name) && entries.get(name)!.version !== version) throw new Error(`Conflicting shadcn dependency versions for ${name}.`);
        entries.set(name, { version, kind: ['react', 'react-dom', 'vue'].includes(name) ? 'peerDependency' : 'dependency' });
      }
    } else validateSubstitution({ component: entry.component, [framework]: entry.source });
    if (entry.packageContentHash !== undefined && !CONTENT_HASH.test(entry.packageContentHash)) throw new Error(`Team package ${entry.source.package} has an invalid content hash.`);
    if (!entry.mappingId || components.has(entry.component)) throw new Error('Substitution provenance must name one mapping per component.');
    components.add(entry.component);
    if (entry.source.shadcn) continue;
    const name = substitutionPackage(entry.source.package!);
    if (dependencyCatalogEntry(name)) throw new Error(`Team substitution cannot replace catalog dependency ${name}.`);
    if (!EXACT_VERSION.test(entry.source.version!)) throw new Error(`Team dependency ${name} needs an exact semantic version.`);
    if (entries.has(name) && entries.get(name)!.version !== entry.source.version) throw new Error(`Conflicting team dependency versions for ${name}.`);
    entries.set(name, { version: entry.source.version!, kind: 'dependency' });
    imports.add(entry.source.package!);
  }
  return { entries, imports, localImports };
}

function resolveDependencies(
  framework: CodegenFramework,
  importSpecifiers: readonly string[],
  substitutions: readonly EmittedSubstitution[] = [],
): GeneratedDependency[] {
  const team = substitutionCatalog(framework, substitutions);
  const packageNames = new Set(frameworkPeers(framework));

  for (const specifier of importSpecifiers) {
    if (team.localImports.has(specifier)) continue;
    const packageName = packageNameFromSpecifier(specifier);
    if (!packageName) {
      throw new Error(`Generated import '${specifier}' is not a portable package import.`);
    }
    if (!dependencyCatalogEntry(packageName) && !team.entries.has(packageName)) {
      throw new Error(`Generated import '${packageName}' has no exact dependency manifest entry.`);
    }
    if (!frameworkImports(framework).has(specifier) && !team.imports.has(specifier)) {
      throw new Error(`Generated import '${specifier}' is not a supported ${framework} artifact import.`);
    }
    packageNames.add(packageName);
  }

  return [...packageNames]
    .map((name): GeneratedDependency => {
      const entry = team.entries.get(name) ?? dependencyCatalogEntry(name);
      if (!entry) {
        throw new Error(`Generated import '${name}' has no exact dependency manifest entry.`);
      }
      return { name, version: entry.version, kind: entry.kind };
    })
    .sort((left, right) => compareCodePoint(`${left.kind}:${left.name}`, `${right.kind}:${right.name}`));
}

export function validateGeneratedArtifact(artifact: GeneratedArtifact): string[] {
  const issues: string[] = [];
  let team: ReturnType<typeof substitutionCatalog>;
  try { team = substitutionCatalog(artifact.framework, artifact.substitutions); }
  catch (error) { return [error instanceof Error ? error.message : String(error)]; }
  if (artifact.schemaVersion !== GENERATED_ARTIFACT_SCHEMA_VERSION) {
    issues.push(`Unsupported artifact schemaVersion '${artifact.schemaVersion}'.`);
  }
  if (artifact.files.length === 0) {
    issues.push('Generated artifact contains no files.');
  }

  const paths = new Set<string>();
  let previousPath = '';
  for (const file of artifact.files) {
    const segments = file.path.split('/');
    if (
      file.path.length === 0
      || file.path.startsWith('/')
      || file.path.includes('\\')
      || segments.includes('')
      || segments.includes('.')
      || segments.includes('..')
    ) {
      issues.push(`Generated file path '${file.path}' is not a safe relative POSIX path.`);
    }
    if (paths.has(file.path)) issues.push(`Generated file path '${file.path}' is duplicated.`);
    paths.add(file.path);
    if (previousPath && compareCodePoint(previousPath, file.path) > 0) {
      issues.push('Generated files are not ordered by path.');
    }
    previousPath = file.path;

    if (file.encoding !== undefined && file.encoding !== 'base64') issues.push(`Generated file '${file.path}' has an unsupported encoding.`);
    if (file.encoding === 'base64' && Buffer.from(file.contents, 'base64').toString('base64') !== file.contents) issues.push(`Generated file '${file.path}' has invalid base64 contents.`);
    const expectedHash = contentHash(file.contents);
    if (!CONTENT_HASH.test(file.contentHash) || file.contentHash !== expectedHash) {
      issues.push(`Generated file '${file.path}' has an invalid contentHash.`);
    }
  }

  // A portable application must close local imports as well as package imports.
  for (const file of artifact.files) {
    const importPattern = /\b(?:import|export)\s+(?:type\s+)?(?:[^'";]*?\sfrom\s*)?['"]([^'"]+)['"]/g;
    for (const match of file.contents.matchAll(importPattern)) {
      const specifier = match[1]!;
      if (!specifier.startsWith('.')) continue;
      const target = posix.normalize(posix.join(posix.dirname(file.path), specifier));
      const candidates = [target, ...['.ts', '.tsx', '.js', '.jsx', '.vue', '.css'].map((extension) => target + extension), target.replace(/\.js$/, '.ts'), target + '/index.ts'];
      if (!candidates.some((candidate) => paths.has(candidate))) issues.push(`Generated local import '${specifier}' in '${file.path}' has no artifact file.`);
    }
  }

  const dependencyNames = new Set<string>();
  let previousDependencyKey = '';
  for (const dependency of artifact.dependencies) {
    const key = `${dependency.kind}:${dependency.name}`;
    if (!PACKAGE_NAME.test(dependency.name)) {
      issues.push(`Dependency '${dependency.name}' is not a package name.`);
    }
    if (!EXACT_VERSION.test(dependency.version)) {
      issues.push(`Dependency '${dependency.name}' must use an exact semantic version.`);
    }
    if (dependencyNames.has(dependency.name)) {
      issues.push(`Dependency '${dependency.name}' is duplicated.`);
    }
    dependencyNames.add(dependency.name);
    if (previousDependencyKey && compareCodePoint(previousDependencyKey, key) > 0) {
      issues.push('Generated dependencies are not ordered by kind and name.');
    }
    previousDependencyKey = key;

    const catalogEntry = team.entries.get(dependency.name) ?? dependencyCatalogEntry(dependency.name);
    if (!catalogEntry) {
      issues.push(`Dependency '${dependency.name}' is not in the generated-artifact catalog.`);
    } else if (
      dependency.version !== catalogEntry.version
      || dependency.kind !== catalogEntry.kind
    ) {
      issues.push(`Dependency '${dependency.name}' does not match its exact catalog entry.`);
    }
  }

  const emittedSpecifiers = collectBareImportSpecifiers(artifact.files);
  for (const specifier of (artifact.substitutions ?? []).map(entry => sourceSpecifier(entry.source))) if (!emittedSpecifiers.includes(specifier)) issues.push(`Substitution import ${specifier} is not emitted.`);
  for (const specifier of emittedSpecifiers) {
    if (!frameworkImports(artifact.framework).has(specifier) && !team.imports.has(specifier)) {
      issues.push(`Generated import '${specifier}' is not supported for ${artifact.framework}.`);
    }
  }
  const expectedDependencies = new Set([
    ...emittedSpecifiers.filter(specifier => !team.localImports.has(specifier)).map((specifier) => packageNameFromSpecifier(specifier)!),
    ...frameworkPeers(artifact.framework),
  ]);
  for (const name of expectedDependencies) {
    if (!dependencyNames.has(name)) {
      issues.push(`Generated import '${name}' is missing from the dependency manifest.`);
    }
  }
  for (const name of dependencyNames) {
    if (!expectedDependencies.has(name)) {
      issues.push(`Dependency '${name}' is not required by the generated artifact.`);
    }
  }

  const actionNames = new Set<string>();
  let previousActionKey = '';
  if (!Array.isArray(artifact.actions)) {
    issues.push('Generated artifact must declare its required domain actions.');
  }
  for (const action of artifact.actions ?? []) {
    const key = actionKey(action);
    if (action.name.length === 0) {
      issues.push('Generated action name must not be empty.');
    } else if (!JAVASCRIPT_IDENTIFIER.test(action.name)) {
      issues.push(`Generated action '${action.name}' is not a safe JavaScript identifier.`);
    }
    if (actionNames.has(action.name)) {
      issues.push(`Generated action '${action.name}' has more than one contract entry.`);
    }
    actionNames.add(action.name);
    if (previousActionKey && compareCodePoint(previousActionKey, key) > 0) {
      issues.push('Generated actions are not ordered by name.');
    }
    previousActionKey = key;

    const parameterNames = new Set<string>();
    for (const parameter of action.parameters) {
      if (parameter.name.length === 0) {
        issues.push(`Generated action '${action.name}' has an unnamed parameter.`);
      }
      if (parameter.type.length === 0) {
        issues.push(
          `Generated action '${action.name}' parameter '${parameter.name}' must declare a type.`,
        );
      }
      if (parameterNames.has(parameter.name)) {
        issues.push(
          `Generated action '${action.name}' duplicates parameter '${parameter.name}'.`,
        );
      }
      parameterNames.add(parameter.name);
    }

    if (action.sources.length === 0) {
      issues.push(`Generated action '${action.name}' must name at least one schema declaration source.`);
    }
    const sourceKeys = new Set<string>();
    let previousSourceKey = '';
    for (const source of action.sources) {
      const sourceKey = actionSourceKey(source);
      if (source.nodeId.length === 0) {
        issues.push(`Generated action '${action.name}' must name each declaring node.`);
      }
      if (source.component.length === 0) {
        issues.push(`Generated action '${action.name}' must name each declaring component.`);
      }
      if (source.event.length === 0) {
        issues.push(`Generated action '${action.name}' must name each declared event.`);
      }
      if (sourceKeys.has(sourceKey)) {
        issues.push(
          `Generated action '${action.name}' duplicates the ${source.nodeId}/${source.event} source.`,
        );
      }
      sourceKeys.add(sourceKey);
      if (previousSourceKey && compareCodePoint(previousSourceKey, sourceKey) > 0) {
        issues.push(
          `Generated action '${action.name}' sources are not ordered by node, event, and component.`,
        );
      }
      previousSourceKey = sourceKey;
    }
  }

  // Emitters place hash-bound markers beside generated action declarations and
  // named markers beside behavior handlers. They make source-only regressions
  // mechanically visible:
  // deleting an action from metadata while its binding remains, and changing a
  // domain handler so it no longer forwards to its own consumer action.
  const declaredActionMarkers = new Map<string, { digest: string; contents: string }>();
  const declaredSourceMarkers = new Set<string>();
  const domainBindingMarkers = new Set<string>();
  for (const file of artifact.files) {
    const actionMarkerPattern = /\/\* @oods-domain-action ([$_\p{ID_Start}][$_\u200c\u200d\p{ID_Continue}]*) (sha256:[a-f0-9]{64}) \*\//gu;
    for (const match of file.contents.matchAll(actionMarkerPattern)) {
      const name = match[1]!;
      const digest = match[2]!;
      if (declaredActionMarkers.has(name)) {
        issues.push(`Generated action marker '${name}' is duplicated.`);
      }
      declaredActionMarkers.set(name, { digest, contents: file.contents });
    }

    const sourceMarkerPattern = /\/\* @oods-domain-source (sha256:[a-f0-9]{64}) \*\//g;
    for (const match of file.contents.matchAll(sourceMarkerPattern)) {
      const digest = match[1]!;
      if (declaredSourceMarkers.has(digest)) {
        issues.push(`Generated domain-source marker '${digest}' is duplicated.`);
      }
      declaredSourceMarkers.add(digest);
    }

    const bindingMarkerPattern = /\/\* @oods-(local|domain)-binding ([$_\p{ID_Start}][$_\u200c\u200d\p{ID_Continue}]*) \*\//gu;
    for (const match of file.contents.matchAll(bindingMarkerPattern)) {
      const kind = match[1]!;
      const name = match[2]!;
      if (kind === 'domain') domainBindingMarkers.add(name);
      const remainder = file.contents.slice((match.index ?? 0) + match[0].length);
      const line = remainder.split('\n', 1)[0] ?? '';
      const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const handler = line.match(new RegExp(
        `^\\s*const\\s+${escapedName}\\s*=.*?=>\\s*\\{(.*?)\\};\\s*$`,
      ));
      if (!handler) {
        issues.push(`Generated binding handler '${name}' is not a canonical executable arrow function.`);
        continue;
      }
      const body = handler[1]?.trim() ?? '';
      const forwardingCall = new RegExp(
        `^actions\\.${escapedName}\\s*\\([^;{}]*\\)\\s*;?$`,
        'u',
      );
      if (kind === 'domain' && !forwardingCall.test(body)) {
        issues.push(
          `Generated domain binding handler '${name}' must forward to actions.${name}.`,
        );
      } else if (kind === 'local' && !localHandlerWritesOwnState(
        artifact.framework, name, line, body, file.contents,
      )) {
        issues.push(`Generated local binding handler '${name}' must update its own state from its input or dismiss it.`);
      }
    }
  }
  // HTML has no runnable binding surface. React and Vue must bind their
  // metadata to generated typed declarations and schema-source provenance.
  if (artifact.framework !== 'html') {
    for (const [name] of declaredActionMarkers) {
      if (!actionNames.has(name)) {
        issues.push(`Generated action marker '${name}' is missing from artifact actions.`);
      }
    }
    for (const action of artifact.actions ?? []) {
      const marker = declaredActionMarkers.get(action.name);
      if (!marker) {
        issues.push(`Artifact action '${action.name}' is missing its generated typed declaration.`);
        continue;
      }
      if (marker.digest !== generatedActionContractDigest(action)) {
        issues.push(`Generated action marker '${action.name}' does not match its artifact contract.`);
      }
      if (!marker.contents.includes(generatedActionTypeSignature(action))) {
        issues.push(`Generated action '${action.name}' is missing its exact typed member signature.`);
      }
      if (!domainBindingMarkers.has(action.name)) {
        issues.push(`Artifact action '${action.name}' is missing its generated domain binding handler.`);
      }
    }
    for (const name of domainBindingMarkers) {
      if (!actionNames.has(name)) {
        issues.push(`Generated domain binding '${name}' is missing from artifact actions.`);
      }
    }

    const expectedSourceMarkers = new Set(
      (artifact.actions ?? []).flatMap((action) => action.sources.map(
        (source) => generatedActionSourceDigest(action.name, source),
      )),
    );
    for (const digest of declaredSourceMarkers) {
      if (!expectedSourceMarkers.has(digest)) {
        issues.push(`Generated domain-source marker '${digest}' is absent from artifact metadata.`);
      }
    }
    for (const digest of expectedSourceMarkers) {
      if (!declaredSourceMarkers.has(digest)) {
        issues.push(`Artifact domain source '${digest}' is missing from generated declarations.`);
      }
    }
  }

  const { contentHash: _contentHash, ...payload } = artifact;
  const expectedArtifactHash = contentHash(canonicalPayload(payload));
  if (!CONTENT_HASH.test(artifact.contentHash) || artifact.contentHash !== expectedArtifactHash) {
    issues.push('Generated artifact has an invalid contentHash.');
  }

  return issues;
}

type BuildGeneratedArtifactInput = {
  substitutions?: EmittedSubstitution[];
  framework: CodegenFramework;
  imports: readonly string[];
  actions?: readonly GeneratedArtifactAction[];
} & (
  | { code: string; fileExtension: string; files?: never }
  | { files: ReadonlyArray<{ path: string; contents: string; encoding?: 'base64' }>; code?: never; fileExtension?: never }
);

export function buildGeneratedArtifact(input: BuildGeneratedArtifactInput): GeneratedArtifact {
  const sourceFiles = input.files ?? [{
    path: artifactPath(input.framework, input.fileExtension),
    contents: input.code,
  }];
  const files: GeneratedArtifactFile[] = sourceFiles
    .map((file) => ({
      ...file,
      contentHash: contentHash(file.contents),
    }))
    .sort((left, right) => compareCodePoint(left.path, right.path));
  const dependencies = resolveDependencies(input.framework, input.imports, input.substitutions);
  const actions: GeneratedArtifactAction[] = (input.actions ?? [])
    .map((action): GeneratedArtifactAction => {
      const sources = action.sources
        .map((source) => ({ ...source }))
        .sort((left, right) => compareCodePoint(actionSourceKey(left), actionSourceKey(right)));
      return {
        name: action.name,
        parameters: action.parameters.map((parameter) => ({ ...parameter })),
        sources: [sources[0]!, ...sources.slice(1)],
      };
    })
    .sort((left, right) => compareCodePoint(actionKey(left), actionKey(right)));
  const payload: Omit<GeneratedArtifact, 'contentHash'> = {
    ...(input.substitutions?.length ? { substitutions: input.substitutions } : {}),
    schemaVersion: GENERATED_ARTIFACT_SCHEMA_VERSION,
    framework: input.framework,
    files,
    dependencies,
    actions,
  };
  const artifact: GeneratedArtifact = {
    ...payload,
    contentHash: contentHash(canonicalPayload(payload)),
  };
  const issues = validateGeneratedArtifact(artifact);
  if (issues.length > 0) {
    throw new Error(`Invalid generated artifact: ${issues.join(' ')}`);
  }
  return artifact;
}

/** Bind a preview's measured package payload into its module identity without changing its generated sources. */
export function bindSubstitutionPackages(artifact: GeneratedArtifact, packages: Array<{ name: string; version: string; contentHash: string; shadcn?: import('../tools/map.shadcn.js').InspectedShadcn }>): GeneratedArtifact {
  if (!artifact.substitutions?.length) return artifact;
  const { contentHash: _hash, ...payload } = artifact;
  const substitutions = artifact.substitutions.map(entry => {
    const found = packages.find(item => item.name === (entry.source.shadcn ? sourceSpecifier(entry.source) : substitutionPackage(entry.source.package!)) && (entry.source.shadcn || item.version === entry.source.version));
    if (!found) throw new Error(`No package identity for ${entry.source.package}@${entry.source.version}`);
    const { project: _project, ...closure } = found.shadcn ?? { project: '', ...entry.source.shadcn };
    return { ...entry, ...(entry.source.shadcn ? { source: { ...entry.source, shadcn: { ...entry.source.shadcn, ...closure, closureHash: found.contentHash } } } : {}), packageContentHash: found.contentHash };
  });
  const bound = { ...payload, substitutions, ...(substitutions.some(entry => entry.source.shadcn) ? { dependencies: resolveDependencies(artifact.framework, collectBareImportSpecifiers(artifact.files), substitutions) } : {}) };
  const result = { ...bound, contentHash: contentHash(canonicalPayload(bound)) };
  const issues = validateGeneratedArtifact(result);
  if (issues.length) throw new Error(issues.join('; '));
  return result;
}
