name: Chromatic Visual Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - "**"
    paths:
      - '.storybook/**'
      - 'src/**/*.stories.@(js|jsx|tsx|mdx)'
      - 'apps/**/stories/**'
      - 'chromatic.config.json'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"
    paths:
      - '.storybook/**'
      - 'src/**/*.stories.@(js|jsx|tsx|mdx)'
      - 'apps/**/stories/**'
      - 'chromatic.config.json'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: chromatic-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Chromatic Visual Regression
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # Run on push/PR/manual without label gating
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    # Run from repository root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      # Token validation is implicit via the job-level if condition above

      - name: Cache Storybook build cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/storybook
          key: ${{ runner.os }}-sb-cache-${{ hashFiles('package-lock.json', '.storybook/**', 'src/**', 'apps/**') }}
          restore-keys: |
            ${{ runner.os }}-sb-cache-

      - name: Build Storybook (static)
        run: npm run build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        if: ${{ env.CHROMATIC_PROJECT_TOKEN != '' }}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: .
          storybookBuildDir: storybook-static
          onlyChanged: true
          autoAcceptChanges: main
          exitZeroOnChanges: true
          prComment: true
