import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { afterEach, expect, it } from 'vitest';
import { handle as generate } from '../../src/tools/code.generate.js';
import { GENERATED_DEPENDENCY_CATALOG } from '../../src/codegen/artifact-envelope.js';
import { reuseFoundationPackages } from '../../../../scripts/product-reality/s182-m04-consumer-harness.mjs';

const root = path.resolve(import.meta.dirname, '../../../..');
const names = ['tokens', 'component-contracts', 'component-styles', 'components-react', 'components-vue'];
const read = (name: string) => JSON.parse(fs.readFileSync(path.join(root, 'packages', name, 'package.json'), 'utf8'));
const scratches: string[] = [];
afterEach(() => scratches.splice(0).forEach(dir => fs.rmSync(dir, { recursive: true, force: true })));

it('unchanged generated app pins and the new exact release cross-pins close over the same five public packages', async () => {
  const found = new Set<string>();
  // s233 preserves generated bytes; the five new libraries still cross-pin this release exactly.
  const visit = (dependencies: Record<string, string>, artifact = false) => {
    for (const [name, version] of Object.entries(dependencies)) {
      if (!name.startsWith('@oods/')) continue;
      expect(version, name).toBe(artifact ? '0.6.2' : read('foundry').version);
      if (found.has(name)) continue;
      found.add(name);
      const manifest = read(name.slice(6));
      expect(manifest.version).toBe(read('foundry').version);
      expect(manifest.private).toBeUndefined();
      expect(manifest.publishConfig).toEqual({ access: 'public' });
      expect(manifest.license).toBe('Apache-2.0');
      for (const file of ['LICENSE', 'NOTICE', 'README.md']) expect(manifest.files).toContain(file);
      visit(manifest.dependencies ?? {});
    }
  };
  for (const framework of ['react', 'vue'] as const) {
    const result = await generate({ framework, schema: { version: '2026.09', screens: [{ id: 'button', component: 'Button', props: { content: 'Save' } }] }, options: { output: 'application' } });
    expect(result.status, JSON.stringify(result.errors)).toBe('ok');
    const manifest = JSON.parse(result.artifact!.files.find(file => file.path === 'package.json')!.contents);
    visit(manifest.dependencies, true);
  }
  expect([...found].sort()).toEqual(names.map(name => `@oods/${name}`).sort());
  for (const [name, dependency] of Object.entries(GENERATED_DEPENDENCY_CATALOG)) {
    if (name.startsWith('@oods/')) expect(dependency.version).toBe('0.6.2');
  }
  expect(read('foundry').version).toBe(JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version);
});

it('a sweep reuses the frozen bytes and refuses damaged or substituted packages before running a cell', async () => {
  fs.mkdirSync(path.join(root, '.tmp'), { recursive: true });
  const scratch = fs.mkdtempSync(path.join(root, '.tmp/s218-freeze-test-')); scratches.push(scratch);
  const frozen = path.join(scratch, 'freeze'), submitted = path.join(frozen, 'submitted-packages');
  fs.mkdirSync(submitted, { recursive: true });
  const records = names.map(name => {
    const source = path.join(scratch, name, 'package'); fs.mkdirSync(source, { recursive: true });
    fs.writeFileSync(path.join(source, 'package.json'), JSON.stringify({ name: `@oods/${name}`, version: '0.3.0' }));
    const artifactPath = `submitted-packages/${name}.tgz`, file = path.join(frozen, artifactPath);
    execFileSync('tar', ['-czf', file, '-C', path.dirname(source), 'package']);
    return { name: `@oods/${name}`, version: '0.3.0', artifactPath, sha256: createHash('sha256').update(fs.readFileSync(file)).digest('hex') };
  });
  const inventory = path.join(submitted, 'inventory.json');
  fs.writeFileSync(inventory, JSON.stringify(records));
  await reuseFoundationPackages(path.join(scratch, 'good'), frozen);
  for (const record of records) expect(fs.readFileSync(path.join(scratch, 'good', record.artifactPath))).toEqual(fs.readFileSync(path.join(frozen, record.artifactPath)));
  fs.appendFileSync(path.join(frozen, records[0]!.artifactPath), 'damage');
  await expect(reuseFoundationPackages(path.join(scratch, 'damaged'), frozen)).rejects.toThrow(/digest differs/);
  records.shift(); fs.writeFileSync(inventory, JSON.stringify(records));
  await expect(reuseFoundationPackages(path.join(scratch, 'missing'), frozen)).rejects.toThrow(/population differs/);
});
